omnihook: Invoke each hook once, passing all stdin
Previously, we invoked each hook once per line of standard input and
drip-fed it that line. This was straightforward and avoided the need to
pool the input, but it altered the effective behavior of hooks designed
to process all standard input before exiting (like my own!). Such hooks
essentially sprouted fail-fast behavior spontaneously because they only
saw one line of standard input per invocation.

Now, if expecting standard input, save it to a temporary file, then
invoke each hook only once, with the file on standard input; this avoids
the errant fail-fast behavior. Increased access to persistent storage
might slow things down, but in practice that might not be perceptible.
Likewise for any increase in required storage. (As a bonus, for H hooks
and L lines of standard input, we now spawn H direct child processes,
down from H × L.)

The alternative was to store the standard input in a variable and pass
it to the hooks in a here-document. The code would have been simpler,
but memory usage would have been less predictable. It might have been
faster, but many shells implement here-documents via temporary files
anyway and would have incurred a similar access penalty.

diff --git a/omnihook b/omnihook
--- a/omnihook
+++ b/omnihook
@@ -21,26 +21,36 @@ hooks_dir=${hooks_dir%??}
 # Git executes hooks "normally", so $0 should contain the pathname.
 hooks_prefix=${0##*/}
 
+# If receiving data on standard input, save it to be repeatedly fed to the
+# invoked hooks later. Using a temporary file is more complicated and possibly
+# slower than using a variable and here-document, but it ensures predictable
+# memory usage.
 case $hooks_prefix in
     post-receive | post-rewrite | pre-push | pre-receive)
-        # At least one line is coming on standard input, so send them through.
-        cat
+        # https://mywiki.wooledge.org/BashFAQ/062
+        # https://mywiki.wooledge.org/SignalTrap
+        hostname=${HOSTNAME:-${HOST:-$(hostname 2>/dev/null)}}
+        tmpfile=~/.${hooks_prefix}${hostname:+_$hostname}_$$.tmp
+        rm -f -- "$tmpfile" || exit
+        trap 'rm -f -- "$tmpfile"' EXIT
+        for sig in HUP INT QUIT TERM; do
+            # Let the shell produce its "killed by signal" exit status.
+            trap 'rm -f -- "$tmpfile"; trap - '$sig'; kill -s '$sig' $$' $sig
+        done
+        cat >"$tmpfile" || exit
         ;;
     *)
-        # Nothing's coming on standard input, so avoid blocking on it, but
-        # coax one iteration out of the `while` loop.
-        echo
+        tmpfile=
         ;;
-esac | while IFS= read -r line; do
-    for hook in "$hooks_dir/$hooks_prefix"-*; do
-        # Ignore nonexecutable hooks because Git does. Technically there's
-        # a TOCTOU bug here, but I don't think it's worth worrying about.
-        if [ -f "$hook" ] && [ -x "$hook" ]; then
-            # https://mywiki.wooledge.org/BashFAQ/024 - If the enclosing
-            # `while` loop runs in a subshell, then `exit` terminates that
-            # subshell only, not the entire program. This only matters if code
-            # is ever added after the `while` loop.
-            printf %s\\n "$line" | "$hook" "$@" || exit
-        fi
-    done
+esac
+
+for hook in "$hooks_dir/$hooks_prefix"-*; do
+    # Ignore nonexecutable hooks because Git does. Technically there's
+    # a TOCTOU bug here, but I don't think it's worth worrying about.
+    [ -f "$hook" ] && [ -x "$hook" ] || continue
+    if [ -n "$tmpfile" ]; then
+        "$hook" "$@" <"$tmpfile"
+    else
+        "$hook" "$@"
+    fi || exit
 done
