require-sigs: Rewrite in POSIX shell
I'd hoped that the awk rewrite [*] would yield a significant improvement
over shell. Unfortunately, due to the natures of the input and task, the
awk implementation was just as complex as the shell implementation with
which I am replacing it now, and it had its own peculiarities that had
to be worked around and explained. I didn't even benefit from awk's
speed because I rarely push more than a handful of commits at a time.

The shell replacement is just as portable, feels more natural in some
ways, and is more amenable to additional `git` calls, which might be
necessary for future improvements.

(Incidentally, fix a bug wherein the "blocked push to ..." error message
would be printed before the first range of commits only, instead of
before each range.)

    [*]: f9c0234 (Redesign and rewrite entire system, 2020-03-16)

diff --git a/pre-push-require-sigs b/pre-push-require-sigs
--- a/pre-push-require-sigs
+++ b/pre-push-require-sigs
@@ -8,61 +8,54 @@
 #
 # See also: https://git-scm.com/docs/githooks/2.24.0#_pre_push
 
-# Ideally this would just be an awk script starting with
-#   #!/usr/bin/env awk -f
-# but shebangs with multiple arguments don't work on some systems
-# (https://www.in-ulm.de/~mascheck/various/shebang/#splitting).
 
+exec >&2
 
-# Use a heredoc instead of single quotes so I don't have to avoid single
-# quotes in the script itself.
-script=$(cat <<\EOF
-    BEGIN {
-        orig_RS = RS
-        exit_status = 0
-    }
+# Git prepends its exec directory to PATH, so this just works.
+. git-sh-setup
 
-    # Fields are 1) local ref, 2) local SHA1, 3) remote ref, 4) remote SHA1.
-    # Ignore pushes that delete remote refs, since no commits are sent.
-    $2 != "0000000000000000000000000000000000000000" {
-        if ($4 == "0000000000000000000000000000000000000000")
-            range = $2              # Creating new remote ref.
-        else
-            range = $4 ".." $2      # Updating existing remote ref.
+exit_status=0
+while read -r local_ref local_sha1 remote_ref remote_sha1; do
+    if [ "$local_sha1" = 0000000000000000000000000000000000000000 ]; then
+        # Deleting a remote ref doesn't push any commits.
+        continue
+    elif [ "$remote_sha1" = 0000000000000000000000000000000000000000 ]; then
+        # Creating new remote ref.
+        range=$local_sha1
+    else
+        # Updating existing remote ref.
+        range=$remote_sha1..$local_sha1
+    fi
 
-        # Treat "commit [SHA1]\n[signature status]" as a single record by
-        # outputting extra newlines and setting RS to a null string.
-        git_rev_list_cmd = "git rev-list --pretty=%G?%n " range
-        RS = ""
-        while (git_rev_list_cmd | getline commit_record) {
-            split(commit_record, commit_fields)
-            sha1 = commit_fields[2]
-            sig_status = commit_fields[3]
+    git rev-list --pretty='%H %G?' "$range" | {
+        range_blocked=no
 
-            if (sig_status ~ /^[GUXYR]$/)
-                continue
+        # Every other line is "commit [full SHA1]", which we don't want. (Only
+        # the "oneline" pretty-format omits them.)
+        while read -r && read -r hash sig_status; do
+            # See the git-rev-list(1) man page for possible outputs of '%G?'.
+            case $sig_status in
+                [GUXYR]) continue ;;
+                B) sig_status_msg='bad signature' ;;
+                E) sig_status_msg="cannot check signature" ;;
+                N) sig_status_msg='no signature' ;;
+                *) sig_status_msg='unknown signature status' ;;
+            esac
 
-            if (exit_status == 0) {
-                printf "%s: blocked push to %s\n", hook_name, $3
-                printf "%s: commits in %s without good signatures:\n",
-                       hook_name, $1
-                exit_status = 1
-            }
+            if [ "$range_blocked" = no ]; then
+                printf '%s: blocked push to %s\n' "${0##*/}" "$remote_ref"
+                printf '%s: commits in %s without good signatures:\n' \
+                    "${0##*/}" "$local_ref"
+                range_blocked=yes
+            fi
 
-            printf "  %s - %s\n", sha1, \
-                   (sig_status == "B") ? "bad signature" : \
-                   (sig_status == "E") ? "signature cannot be checked" : \
-                   (sig_status == "N") ? "no signature" : \
-                                         "unknown signature status"
-        }
-        close(git_rev_list_cmd)
+            printf '  %s - %s\n' "$hash" "$sig_status_msg"
+        done
 
-        # Restore original RS for reading standard input.
-        RS = orig_RS
-    }
-
-    END { exit exit_status }
-EOF
-)
-
-exec >&2 awk "$script" hook_name="$(basename -- "$0")"
+        # https://mywiki.wooledge.org/BashFAQ/024 - The enclosing command
+        # grouping may run in a subshell, so use the exit status of the
+        # pipeline to set 'exit_status' on the outside.
+        [ "$range_blocked" = no ]
+    } || exit_status=1
+done
+exit $exit_status
